export const colombiaData = [
  { id: 0, departamento: "Amazonas", ciudades: ["Leticia", "Puerto Nariño"] },
  { id: 1, departamento: "Antioquia", ciudades: ["Medellín", "Bello", "Envigado", "Itagüí", "Sabaneta"] },
  { id: 2, departamento: "Arauca", ciudades: ["Arauca", "Arauquita", "Saravena", "Tame"] },
  { id: 3, departamento: "Atlántico", ciudades: ["Barranquilla", "Soledad", "Malambo", "Sabanalarga"] },
  { id: 4, departamento: "Bolívar", ciudades: ["Cartagena", "Magangué", "Turbaco", "El Carmen de Bolívar"] },
  { id: 5, departamento: "Boyacá", ciudades: ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá"] },
  { id: 6, departamento: "Caldas", ciudades: ["Manizales", "La Dorada", "Chinchiná", "Villamaría"] },
  { id: 7, departamento: "Caquetá", ciudades: ["Florencia", "San Vicente del Caguán", "Cartagena del Chairá"] },
  { id: 8, departamento: "Casanare", ciudades: ["Yopal", "Aguazul", "Villanueva", "Paz de Ariporo"] },
  { id: 9, departamento: "Cauca", ciudades: ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Patía"] },
  { id: 10, departamento: "Cesar", ciudades: ["Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia"] },
  { id: 11, departamento: "Chocó", ciudades: ["Quibdó", "Istmina", "Tadó", "Condoto"] },
  { id: 12, departamento: "Cundinamarca", ciudades: ["Bogotá", "Soacha", "Fusagasugá", "Facatativá", "Chía", "Zipaquirá", "Girardot"] },
  { id: 13, departamento: "Córdoba", ciudades: ["Montería", "Cereté", "Sahagún", "Lorica"] },
  { id: 14, departamento: "Guainía", ciudades: ["Inírida"] },
  { id: 15, departamento: "Guaviare", ciudades: ["San José del Guaviare", "Calamar", "El Retorno"] },
  { id: 16, departamento: "Huila", ciudades: ["Neiva", "Pitalito", "Garzón", "La Plata"] },
  { id: 17, departamento: "La Guajira", ciudades: ["Riohacha", "Maicao", "Uribia", "San Juan del Cesar"] },
  { id: 18, departamento: "Magdalena", ciudades: ["Santa Marta", "Ciénaga", "Fundación", "El Banco"] },
  { id: 19, departamento: "Meta", ciudades: ["Villavicencio", "Acacías", "Granada", "Puerto López"] },
  { id: 20, departamento: "Nariño", ciudades: ["Pasto", "Tumaco", "Ipiales", "Túquerres"] },
  { id: 21, departamento: "Norte de Santander", ciudades: ["Cúcuta", "Ocaña", "Pamplona", "Los Patios"] },
  { id: 22, departamento: "Putumayo", ciudades: ["Mocoa", "Puerto Asís", "Orito", "Valle del Guamuez"] },
  { id: 23, departamento: "Quindío", ciudades: ["Armenia", "Calarcá", "La Tebaida", "Montenegro"] },
  { id: 24, departamento: "Risaralda", ciudades: ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia"] },
  { id: 25, departamento: "San Andrés y Providencia", ciudades: ["San Andrés"] },
  { id: 26, departamento: "Santander", ciudades: ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta"] },
  { id: 27, departamento: "Sucre", ciudades: ["Sincelejo", "Corozal", "San Marcos", "Tolú"] },
  { id: 28, departamento: "Tolima", ciudades: ["Ibagué", "Espinal", "Melgar", "Mariquita"] },
  { id: 29, departamento: "Valle del Cauca", ciudades: ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago"] },
  { id: 30, departamento: "Vaupés", ciudades: ["Mitú"] },
  { id: 31, departamento: "Vichada", ciudades: ["Puerto Carreño", "La Primavera", "Cumaribo"] }
];

export const boxes = [
    { id: 'box-001', name: 'CrossFit Medellín' },
    { id: 'box-002', name: 'CrossFit Bogotá' },
    { id: 'box-003', name: 'CrossFit Cali' },
    { id: 'box-004', name: 'CrossFit Barranquilla' },
    { id: 'box-005', name: 'CrossFit Cartagena' },
    { id: 'box-006', name: 'CrossFit Bucaramanga' },
    { id: 'box-007', name: 'A-Box CrossFit' },
    { id: 'box-008', name: 'Action CrossFit' },
    { id: 'box-009', name: 'Alliance CrossFit' },
    { id: 'box-010', name: 'Alpha Training' },
];
