import type { Athlete, Competition, Registration, LeaderboardEntry } from './types';

export const athletes: Athlete[] = [
  {
    id: 'ath-001',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar1/200/200',
    idNumber: '123456789',
    phone: '555-0101',
    gender: 'Male',
    country: 'Colombia',
    state: 'Antioquia',
    boxAffiliation: 'CrossFit Medellín',
    coachName: 'Coach Rico',
    socials: { instagram: 'alexj_fit' },
    skillLevel: 'RX',
    personalRecords: {
      'Clean & Jerk': 140,
      'Snatch': 115,
      'Deadlift': 220,
      'Fran': '2:15',
    },
    competitionHistory: [{ competitionName: 'Wodapalooza', placing: 25 }],
  },
  {
    id: 'ath-002',
    name: 'Maria Garcia',
    email: 'maria@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar2/200/200',
    idNumber: '987654321',
    phone: '555-0102',
    gender: 'Female',
    country: 'Colombia',
    state: 'Cundinamarca',
    boxAffiliation: 'CrossFit Bogotá',
    coachName: 'Coach Diaz',
    socials: { instagram: 'mariag_strong' },
    skillLevel: 'RX',
     personalRecords: {
      'Clean & Jerk': 90,
      'Snatch': 70,
      'Deadlift': 150,
      'Fran': '2:50',
    },
    competitionHistory: [{ competitionName: 'Bogota Fitness Challenge', placing: 3 }],
  },
  {
    id: 'ath-003',
    name: 'Carlos Perez',
    email: 'carlos@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar3/200/200',
    idNumber: '555555555',
    phone: '555-0103',
    gender: 'Male',
    country: 'Colombia',
    state: 'Antioquia',
    boxAffiliation: 'CrossFit Medellín',
    coachName: 'Coach Rico',
    socials: { instagram: 'cperez_fit' },
    skillLevel: 'Intermediate',
    personalRecords: {
      'Clean & Jerk': 110,
      'Snatch': 90,
      'Deadlift': 180,
      'Fran': '3:30',
    },
    competitionHistory: [{ competitionName: 'Medellin Throwdown', placing: 10 }],
  },
  {
    id: 'ath-004',
    name: 'Sofia Rodriguez',
    email: 'sofia@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar4/200/200',
    idNumber: '444444444',
    phone: '555-0104',
    gender: 'Female',
    country: 'Colombia',
    state: 'Valle del Cauca',
    boxAffiliation: 'CrossFit Cali',
    coachName: 'Coach Vega',
    socials: { instagram: 'sofia.lifts' },
    skillLevel: 'RX',
     personalRecords: {
      'Clean & Jerk': 95,
      'Snatch': 75,
      'Deadlift': 160,
      'Fran': '2:45',
    },
    competitionHistory: [{ competitionName: 'Cali Fitness Festival', placing: 1 }],
  },
   {
    id: 'ath-005',
    name: 'Daniel Kim',
    email: 'daniel@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar5/200/200',
    idNumber: '333333333',
    phone: '555-0105',
    gender: 'Male',
    country: 'Colombia',
    state: 'Antioquia',
    boxAffiliation: 'CrossFit Envigado',
    coachName: 'Coach Santos',
    socials: { instagram: 'dk_fit' },
    skillLevel: 'RX',
    personalRecords: {
      'Clean & Jerk': 135,
      'Snatch': 110,
      'Deadlift': 210,
      'Fran': '2:25',
    },
    competitionHistory: [{ competitionName: 'Medellin Throwdown', placing: 5 }],
  },
  {
    id: 'ath-006',
    name: 'Laura Chen',
    email: 'laura@example.com',
    avatarUrl: 'https://picsum.photos/seed/avatar6/200/200',
    idNumber: '222222222',
    phone: '555-0106',
    gender: 'Female',
    country: 'Colombia',
    state: 'Cundinamarca',
    boxAffiliation: 'CrossFit Bogotá',
    coachName: 'Coach Diaz',
    socials: { instagram: 'laurachenfit' },
    skillLevel: 'Scaled',
    personalRecords: {
      'Clean & Jerk': 60,
      'Snatch': 45,
      'Deadlift': 100,
      'Fran': '5:00',
    },
    competitionHistory: [],
  },
];

export const competitions: Competition[] = [
  {
    id: 'comp-001',
    name: 'The Titan Games',
    logoUrl: '/logo-placeholder.svg',
    bannerUrl: 'https://picsum.photos/seed/titan/1200/600',
    location: 'Medellín, Colombia',
    startDate: '2024-08-15',
    endDate: '2024-08-17',
    registrationStartDate: '2024-06-01',
    registrationEndDate: '2024-07-31',
    description: 'An epic test of strength and endurance. The Titan Games brings together the best athletes to compete for the title of Titan.',
    rulesUrl: '/titan-games-rules.pdf',
    organizerId: 'org-001',
    categories: [
      { id: 'cat-001', name: 'RX Pairs', type: 'Pairs', gender: 'Mixed', price: 150, spots: 50, registeredCount: 35, requiresPartner: true },
      { id: 'cat-002', name: 'Intermediate Individual', type: 'Individual', gender: 'Male', price: 80, spots: 100, registeredCount: 90, requiresPartner: false },
      { id: 'cat-003', name: 'Scaled Teams', type: 'Team', gender: 'Mixed', price: 280, spots: 30, registeredCount: 15, requiresPartner: true },
    ],
  },
  {
    id: 'comp-002',
    name: 'Coastal Clash',
    logoUrl: '/logo-placeholder.svg',
    bannerUrl: 'https://picsum.photos/seed/coastal/1200/600',
    location: 'Cartagena, Colombia',
    startDate: '2024-09-20',
    endDate: '2024-09-22',
    registrationStartDate: '2024-07-01',
    registrationEndDate: '2024-08-31',
    description: 'Sun, sand, and suffering. A unique fitness competition on the beautiful beaches of Cartagena.',
    rulesUrl: '/coastal-clash-rules.pdf',
    organizerId: 'org-002',
    categories: [
      { id: 'cat-004', name: 'RX Individual', type: 'Individual', gender: 'Female', price: 90, spots: 50, registeredCount: 45, requiresPartner: false },
      { id: 'cat-005', name: 'RX Pairs', type: 'Pairs', gender: 'Male', price: 160, spots: 40, registeredCount: 20, requiresPartner: true },
      { id: 'cat-006', name: 'Intermediate Pairs', type: 'Pairs', gender: 'Mixed', price: 130, spots: 50, registeredCount: 50, requiresPartner: true },
    ],
  },
  {
    id: 'comp-003',
    name: 'Urban Throwdown',
    logoUrl: '/logo-placeholder.svg',
    bannerUrl: 'https://picsum.photos/seed/urban/1200/600',
    location: 'Bogotá, Colombia',
    startDate: '2024-10-11',
    endDate: '2024-10-13',
    registrationStartDate: '2024-08-01',
    registrationEndDate: '2024-09-30',
    description: 'The concrete jungle is your arena. A fast-paced, high-intensity competition in the heart of Bogotá.',
    organizerId: 'org-001',
    categories: [
      { id: 'cat-007', name: 'Elite Individual', type: 'Individual', gender: 'Male', price: 120, spots: 30, registeredCount: 28, requiresPartner: false },
      { id: 'cat-008', name: 'RX Teams of 4', type: 'Team', gender: 'Mixed', price: 400, spots: 20, registeredCount: 19, requiresPartner: true },
    ],
  },
  {
    id: 'comp-004',
    name: 'Mountain Mayhem',
    logoUrl: '/logo-placeholder.svg',
    bannerUrl: 'https://picsum.photos/seed/mountain/1200/600',
    location: 'Manizales, Colombia',
    startDate: '2024-11-01',
    endDate: '2024-11-03',
    registrationStartDate: '2024-09-01',
    registrationEndDate: '2024-10-15',
    description: 'Compete at altitude and conquer the mountains. A true test of grit.',
    organizerId: 'org-003',
    categories: [
       { id: 'cat-009', name: 'RX Pairs', type: 'Pairs', gender: 'Female', price: 150, spots: 30, registeredCount: 10, requiresPartner: true },
    ],
  },
];

export const registrations: Registration[] = [
    {
        id: 'reg-001',
        athleteId: 'ath-001',
        competitionId: 'comp-001',
        categoryId: 'cat-001',
        teamName: 'Titan Slayers',
        tshirtSize: 'L',
        paymentStatus: 'approved',
        paymentProofUrl: '/path/to/proof.jpg'
    },
    {
        id: 'reg-002',
        athleteId: 'ath-002',
        competitionId: 'comp-002',
        categoryId: 'cat-004',
        tshirtSize: 'M',
        paymentStatus: 'pending_approval',
        paymentProofUrl: '/path/to/proof2.jpg'
    },
    {
        id: 'reg-003',
        athleteId: 'ath-003',
        competitionId: 'comp-001',
        categoryId: 'cat-002',
        tshirtSize: 'M',
        paymentStatus: 'pending_payment',
    }
];

export const leaderboardData: LeaderboardEntry[] = [
  {
    rank: 1,
    athleteName: "Alex Johnson & Maria Garcia",
    teamName: "Power Couple",
    totalPoints: 385,
    scores: { 'WOD 1': { score: '10:32', points: 100 }, 'WOD 2': { score: '250 reps', points: 95 }, 'WOD 3': { score: '12:15', points: 95 } }
  },
  {
    rank: 2,
    athleteName: "Carlos Perez & Sofia Rodriguez",
    teamName: "Grit & Grace",
    totalPoints: 380,
    scores: { 'WOD 1': { score: '11:01', points: 95 }, 'WOD 2': { score: '255 reps', points: 100 }, 'WOD 3': { score: '12:05', points: 100 } }
  },
  {
    rank: 3,
    athleteName: "Daniel Kim & Partner",
    teamName: "Lift Heavy",
    totalPoints: 350,
    scores: { 'WOD 1': { score: '11:30', points: 90 }, 'WOD 2': { score: '240 reps', points: 90 }, 'WOD 3': { score: '13:00', points: 90 } }
  },
];


export const currentUser: Athlete = athletes[0];
